"abcdfsp":
  "OAUTH_TOKEN_ENDPOINT": "https://iskm.orcr.mbox-techops.mbox-techops.info.internal:9443/oauth2/token"
  "dfsp_id": "abcdfsp"
  "extgw_client_key": "O9s2WR8UJDaWd2WawUMMgC1VB0wa"
  "extgw_client_secret": "gfZ4NpzVsVSfeNwtRsnLTvTf9RYa"
  "extgw_fqdn": "extgw.orcr.mbox-techops.mbox-techops.info"
  "helm_release_name": "abcdfsp"
  "mcm_auth_enabled": true
  "mcm_auth_pass": "abcdfsp123"
  "mcm_auth_user": "abcdfsp"
  "mcm_host_url": "mcmweb.orcr.mbox-techops.mbox-techops.info"
  "ml_connector_image_tag": "12.0.4"
  "p12_pass_phrase": "samplepass"
  "pm4ml_instance_name": "abcdfsp"
  "pm4ml_subdomain": "mboxtechopsorcrk4s.mbox-techops.mbox-techops.info"
  "private_reg_pass": "changethis"
  "private_reg_url": "modusbox-mbx-docker.jfrog.io"
  "private_reg_user": "mbx-cicd-deployer"
  "tls_outbound_cacert": |
    -----BEGIN CERTIFICATE-----
    MIIGbTCCBFWgAwIBAgIUKf6n6LIXUBGWAvg1K/c7HfxUI2UwDQYJKoZIhvcNAQEL
    BQAwSDERMA8GA1UEChMITW9kdXNCb3gxHDAaBgNVBAsTE0luZnJhc3RydWN0dXJl
    IFRlYW0xFTATBgNVBAMTDG9yY3IgUm9vdCBDQTAeFw0yMTA1MTIxMzA0MjdaFw0y
    NjA1MTExMzA0NTdaMHgxETAPBgNVBAoTCE1vZHVzQm94MRwwGgYDVQQLExNJbmZy
    YXN0cnVjdHVyZSBUZWFtMUUwQwYDVQQDEzxvcmNyLm1ib3gtdGVjaG9wcy5tYm94
    LXRlY2hvcHMuaW5mby5pbnRlcm5hbCBJbnRlcm1lZGlhdGUgQ0EwggIiMA0GCSqG
    SIb3DQEBAQUAA4ICDwAwggIKAoICAQDrNGa4nDfwBPVjfYGeX6Be4HyDXoT1uDO+
    kWl2XuL59eUAazCdXMUdJJNQxw4kZFvCvkQWaRgJd6Q84ttFqGpi939QZr9yu4TH
    20XCaiprRVDvmml0ApzJZrUp6UwUDpQfYgUKbzZgKYs/xa8okURAXyyVBOyc7QmI
    xP3SS/NbpAsBpvVyDfSqk/drfFpBrOC3Srr9Wi5JkmYflxyMytxLM1uqOhS0UU5m
    fi2pihWnGcWP+mE2Vgn8qtGVzn2B4coiX5hsWIvI1o4DBnAmVzUHyIfU0wfdUawM
    CjzPtqxAzsOd9C5q0CfmnzlAW3b6dgVRtSrGdB1MnO9SNDl0kah6zoaFBwybRcEw
    iO14OApTPo72c1cXYU6dhgADb1mAxf4VFHZDyFCsrIAU2hbyph4+ARpCSXTfKGVQ
    MmSlLKApvKBhrLaTRTzZfkgk3JNtD+M49fG5rayVT6NP/OuipYWhNTUXl8ddAsdD
    wHOmpvE/Wknxepp8nOjojbf0Tk1iUqs9FdC67QUuFLYXC/sacgCYhJL+RGU0nvi2
    T4dbCrzMWrA+kSEBqGQbf/M6BbD/OPFVJVlq2W9jd/dVLn62NYkS1UoJ+F04+1pP
    UTUmDFPe7P5ztI3My9xh2Lv+dJPJejlbkj74McoH2CGh6zlXZnxaEqbdg7zAf1fU
    2ytq7A42bwIDAQABo4IBHTCCARkwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQF
    MAMBAf8wHQYDVR0OBBYEFCmn28CJQ4hU93GB9Gc7m/lMXmP7MB8GA1UdIwQYMBaA
    FEjKBcB3bLM8wf63xv+gFR/uPdGLMF8GCCsGAQUFBwEBBFMwUTBPBggrBgEFBQcw
    AoZDaHR0cDovL3ZhdWx0Lm9yY3IubWJveC10ZWNob3BzLm1ib3gtdGVjaG9wcy5p
    bmZvLmludGVybmFsL3YxL3BraS9jYTBVBgNVHR8ETjBMMEqgSKBGhkRodHRwOi8v
    dmF1bHQub3Jjci5tYm94LXRlY2hvcHMubWJveC10ZWNob3BzLmluZm8uaW50ZXJu
    YWwvdjEvcGtpL2NybDANBgkqhkiG9w0BAQsFAAOCAgEAoeHrikS8i2OZ62NSpJG2
    fGV7MalXZ+XepCRoW//SaN/Hgd9MM3f86TdM2toi2yPQsEGQS09OhIMNr1BHJPTE
    Jt8SjMEPNch8j+e7GJKkqqFYQ/xC6jTjx3PrNKbPdxR+3n3AOcpZN5uRjUtOPNaJ
    XNFz8AreSw1729zHG8sAN3746aX9kLnqz86f+ekwEPH/XbtxUJoPpCVa2BkQ83Fe
    fKTSuLBGdvuFOjOcTAEc2JyLbbpS7lySngxFfIkIfcIDJ+h8hycugnXmHYTStfzK
    3vU8uD77ArNn3ATBxx3pztN7FNRvkBkuDMINMZK5eKRKDQWLnKiDc7mJFVdYVKrP
    eYyVxN6a4JK+R15hofr2EzY6PIxa5VNagUbHTGV/at8au9TgyTIKV8BQz5j/ZT7H
    7GZUlvEtpj8Q4w5KAGuxn9D8XGtM/eDPy0P/stDdFChAUdF3+hmgjZiNoJwXvuQ4
    DvTdm5IlrM6mmOeq3q3TOM6gOKFU4DpoWmqCNnYWQnykUsvEgVIEjzDbJdPCVsa7
    iX4c8o9pAqOaqEY1SZdr0+VjGSzI7fmhpQ0PWDsh8N7VgBNbtkyfOHqaRPI/iNl9
    itJmknuyH72xBhExH3UqMsUw8NXYx+mphcJLMOOjvd6I/knfRga8ceho3IjYb+fy
    jAxgzrlVNZNbM3nOJxamLa8=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFXTCCA0WgAwIBAgIRAJnV5Zde6BrayxXBPLH7XfQwDQYJKoZIhvcNAQELBQAw
    SDERMA8GA1UEChMITW9kdXNCb3gxHDAaBgNVBAsTE0luZnJhc3RydWN0dXJlIFRl
    YW0xFTATBgNVBAMTDG9yY3IgUm9vdCBDQTAeFw0yMTA1MTIxMzA0NTVaFw00MTA1
    MDcxMzA0NTVaMEgxETAPBgNVBAoTCE1vZHVzQm94MRwwGgYDVQQLExNJbmZyYXN0
    cnVjdHVyZSBUZWFtMRUwEwYDVQQDEwxvcmNyIFJvb3QgQ0EwggIiMA0GCSqGSIb3
    DQEBAQUAA4ICDwAwggIKAoICAQCqYTo8K34wiL5PaTvovWl14S47y4YJIhWDxGmp
    pH0whXH0gsUInyDm4yRGPBDYFN3+OgbUc2OXkJfX8+E21E4Ls5Fo7z/jfVjgz9OW
    4N41uMAJi9qWhV3DSDs+r5dS2OEm+r8KNlhE9wR9rw75DQTTJ6/ya+sz+4I4ClTN
    CHLFHrpO2hz+3WWbsXKFUQY4ZPt31ERG6+JDnVoilHh4ZVykhhnLmQGM3gfdQ0WS
    6mx4zlXKjGidRQpI4ijHXciX7vCzsxm6pAY3zWNwIvZvhC/R4EajVRYSUKA771VH
    PC1MEj4tU6HgXM2JN+ld1wObVS/OsC1OfJSCmICdyTeccZFteaM7KfTwkv1BbkJS
    PIr9QHn/OIAcjmpLNQ51HAZY/NzddhRQaijNF5zc9jwX/aAm7UyCMQtzc3eny8Hq
    2CRZpdshHBiQx+45wfe8MQKZsdbhx4/0FYFGE9symiCompHQDR2HDNdtqQv+OuRj
    d2r8M1CxX4eME9tv0noNZ/I5T5sj9s5SL7vsZfKq+oQfv+KhGd2InlT4Zyl6WXBz
    7moCmjTE7Qu9JAcWi8IxsIJVEDmBG4TFS9EWl6m+nYzRqhLLb1mtNakO4Sjm83Az
    ntNpZaZHdS2eXSaSv3vY6M2XVlMvt60tG2ssSiOwfBH3H5gm9mZ/0YO9ruDWLh3I
    YqioIwIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAd
    BgNVHQ4EFgQUSMoFwHdsszzB/rfG/6AVH+490YswDQYJKoZIhvcNAQELBQADggIB
    AJngWRExnCSevw0v6TjaYULbB9RgDOWWFBkQoA1bOgaC5be8vHaA9FQU8qdjeZj3
    Fl7r8j6Fq0y2kn8+0oju+O0P86TD/oWGtlzzSYl5uwEAYR8bxAJMSM038Kp6U+0d
    Y5OGYmwxe0wqY/Msv2fWivBdWYS9pu0PDxsIl362g5tNgSt4T3jCqCA3M6cvowIs
    ufy2SnPGGdprx1+YSiboEKjVZxWzOYn+5KDk5eTCV6LDTdq7MoT2mTvTwKKl7aT1
    pM/FDq14UjQW1zdOAnlyxRRCR6/+EJe6Z5/JktFftkOd0PaoFOKOtnyJK+/hmBgW
    Am2B5ppDE0EzLSFilUG9bAYCONNXjKgLKFr0CEkb2KW3pmM41l+jNRWZYOiUr9zu
    UVQiHtEDq8lC8xVj6DaETBKxoDvJxCr4NxMvhJprC9ylmoyAw2rBEnEsciLnkhZn
    TnN7VSTirmlhIjVLcRGTBlJV9pwi9MDM44U2/j8phUF3DeXN70prhECun5hrnTot
    tmJcchXQk98cdwIXdbe+w0ySW/Ly0plK0nQAbCiFtf9bPuS8b4qv76Rpl0yp0iHk
    UiwKFC9iOMInCk2U6oNeeGXztFBDhNUWNwxYCbGRuY/FKQ0hfaxv08h9WOm2bQ8d
    c8NUZVf30ts+zhAK0udg5D3zN/J5gid6rA/TRYgVtjWp
    -----END CERTIFICATE-----
  "tls_outbound_cert": |-
    -----BEGIN CERTIFICATE-----
    MIIGDjCCA/agAwIBAgIUapgpB0b2I/RpMxPZL5fqOMGop6cwDQYJKoZIhvcNAQEL
    BQAweDERMA8GA1UEChMITW9kdXNCb3gxHDAaBgNVBAsTE0luZnJhc3RydWN0dXJl
    IFRlYW0xRTBDBgNVBAMTPG9yY3IubWJveC10ZWNob3BzLm1ib3gtdGVjaG9wcy5p
    bmZvLmludGVybmFsIEludGVybWVkaWF0ZSBDQTAeFw0yMTA1MTIxMzIzMDhaFw0y
    MzA1MTMwMTAxNTVaMGcxETAPBgNVBAoTCE1vZHVzQm94MRwwGgYDVQQLExNJbmZy
    YXN0cnVjdHVyZSBUZWFtMTQwMgYDVQQDEythYmNkZnNwLm9yY3IubWJveC10ZWNo
    b3BzLm1ib3gtdGVjaG9wcy5pbmZvMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
    CgKCAgEAxFlwGa3loKWfCHHUJz6zWfUd4xCiR9LoJWKAoH53S2vwxj76iq3wby7R
    9bCL4Benm6xUfFWYNY5hQ0F2qO8icemqv0cGepzKnY5B67K9XDvO22Hzakc17ZhC
    vWKSABfJaFc/r9UURb/82B/9rjINHdSiMM62XNXIndMPfS4tBorfy14JwPr7Eubb
    Q8f/pHnEfRFYSBDC6iGTa5uDX0ZD0a7SJP2swujnydFHGAvW5qpfupn4vPxyF4px
    itonMfmLXlrjucufPOfygVn8T0h/uQ/JkLWBa8Cy8X/jhejH/0AMwGWTCUk90ofX
    we2VPd0cMgnD2DoF2fVMnksdUO53Hv3U3rrNDMamyDZQJtSYMaz+/+KAELUlTdfL
    4Ba9UAc7JTjsDDnRB9lEzg4+UGbNq5vPm5oWksIW8ou+b5vptmNgmN8tC5cxM7vS
    moxei+HVn4ibF1TtF0FTOdpkBBM2xS/v8kgfBhTg3dQHxfaB5o7MfNhjDD8jwEZv
    Nm9bbiW3y460tcNy7rutAU9A1305our/pwi2/K8e0IlY/uFEUAQtSGtg4JA3JpfQ
    HlbBZY2G+rKjOPVuH5KmQezWsUbrBFn2TmvylHtJniEnr6X3c56p0N6uRgAZjC88
    9Z9K97EaZl6AW4oftHf560lmuyEB/YOhKBMXDCw5x1/Jd68Rlz0CAwEAAaOBoDCB
    nTAOBgNVHQ8BAf8EBAMCA6gwEwYDVR0lBAwwCgYIKwYBBQUHAwIwHQYDVR0OBBYE
    FOjjjW7NQ73jnvL/qvcn2Y+L1qfXMB8GA1UdIwQYMBaAFCmn28CJQ4hU93GB9Gc7
    m/lMXmP7MDYGA1UdEQQvMC2CK2FiY2Rmc3Aub3Jjci5tYm94LXRlY2hvcHMubWJv
    eC10ZWNob3BzLmluZm8wDQYJKoZIhvcNAQELBQADggIBAD7hRl8Ub5dcQK7vLw9F
    Q2gle3ihYUSBvGiQhnt6CRW+2zK1rdXXqxNQi6S6graux+/aJXaZiu18OWq33xSL
    mvR1KG+WwZhufhLIeZr3IuB3+i6lRhoRA2FvaaLc8LbYhwxxPRA7sRFppog7/RG/
    90vp8TWBT90aCYU0O1hSFc88cMN92wDOUECR23oGUyfPZVLZlXUR5ieTzpvCrEzU
    rgD6na++hz7Ahm6qxckjTgRNWVljZrAfyjDbp/jPuJFtCF1gKGg0yrZdiFx2IufX
    o3U/pUMXSIkqg0FPzRpm0Hw/BcAefJZ8Z3w49eZgFef4vyb2nzaoT+b8CvVkOLnN
    PhBCu/U5d0Nmes9pMojA5oDv2YSL2s+EDwhNh83CQHFJY75l39sYouvWfoICBWlt
    IfuPG8mJNOCs0uyMO52KIjpaw/zntTZUvJsU72NqyyB2mQLgxcdB8tfr+d9J64J1
    b7I7e5IbiRNhlk3LIENMavSRY7SHUWuHvlUiyM9kSZAxoNRh17RnZutvX691B7S5
    TahmXBvJl7RcmYFuq9M9WqxJz8S0IYftMAVtEAnaEdOHldXVhEmILn52YuJS5i81
    bEvy+OVU1Djj05oxnguAmJCKQUCvKqJBiRMfV5tEkhiCidCtCYH0oXBS0kmnmFy6
    7u7CyWminiUlkFVTlZKJ5lfe
    -----END CERTIFICATE-----
  "tls_outbound_privkey": |-
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKgIBAAKCAgEAxFlwGa3loKWfCHHUJz6zWfUd4xCiR9LoJWKAoH53S2vwxj76
    iq3wby7R9bCL4Benm6xUfFWYNY5hQ0F2qO8icemqv0cGepzKnY5B67K9XDvO22Hz
    akc17ZhCvWKSABfJaFc/r9UURb/82B/9rjINHdSiMM62XNXIndMPfS4tBorfy14J
    wPr7EubbQ8f/pHnEfRFYSBDC6iGTa5uDX0ZD0a7SJP2swujnydFHGAvW5qpfupn4
    vPxyF4pxitonMfmLXlrjucufPOfygVn8T0h/uQ/JkLWBa8Cy8X/jhejH/0AMwGWT
    CUk90ofXwe2VPd0cMgnD2DoF2fVMnksdUO53Hv3U3rrNDMamyDZQJtSYMaz+/+KA
    ELUlTdfL4Ba9UAc7JTjsDDnRB9lEzg4+UGbNq5vPm5oWksIW8ou+b5vptmNgmN8t
    C5cxM7vSmoxei+HVn4ibF1TtF0FTOdpkBBM2xS/v8kgfBhTg3dQHxfaB5o7MfNhj
    DD8jwEZvNm9bbiW3y460tcNy7rutAU9A1305our/pwi2/K8e0IlY/uFEUAQtSGtg
    4JA3JpfQHlbBZY2G+rKjOPVuH5KmQezWsUbrBFn2TmvylHtJniEnr6X3c56p0N6u
    RgAZjC889Z9K97EaZl6AW4oftHf560lmuyEB/YOhKBMXDCw5x1/Jd68Rlz0CAwEA
    AQKCAgEAlpOMP3U3uzooOt6odyxDeMJcmCzCdthMRZdD01EJBWMS88WKd92qnGlI
    hOVOb51UYTMIW418u92jw2Mpr6YsQTWURzodwtwJGkjlTu70/w2ytlVoyeEwfzQc
    QoacNswHHiiC48JB2LfCHLBz6CnkGzNc6pcsDQe54SbiIvrNds37kEderYsMDtPR
    5So0Z5smT0+E50dLYyg6mPRbDC6jheNOryWHXrYkQ4ZlwhAaTyzrWvwHYE8s49a8
    +mIQWufntIV5TJvWU2wBcqdish6ELJTp3DsFtG/ECyYrgx8geSRSYx3CZAWyDok0
    sjkUEaxGmi0Y7vKYWC0hA+fQ5Kbr3BK2xHTb2HGZOcUF81refgmfe/eswBAAgKxi
    84XZUXnVvEv2/d45kaoz1cuasbAyFd8JW3eOOZTUyUUZLWLpeJ4PF1VZl/7omkIw
    TcgI4p2TnX1GNEjaDtm8YbwSykJcvAcUcreWOK4RYPpYoyb4Vln1wnSTZbPpfUVu
    LKyQqwFxtFC0EGOE1e+R+zpUduA46vGHexM7ZoWR6+Jw4k+4nLQgNx89xIG4DeU9
    w+RI7twbDCp2UeomNlGzrJXEC0rm5t6hd1YDSSC6PyKKDws6VC9kZxkHqXnH883X
    QCIhkiC8yTBeYk0Qgh35eCXOUeyDPb4am5mlsp+uTqIogCYLYlUCggEBAMS7sqna
    umcP+U1lWcjY++SiWCvSRn6ae0GJW6HE53/gWIgphGvjhbJx2VDTjrKzzOSt9FcF
    64aSPM6BvuZgsfa50S3dEHgDSWujrgF0k9ylPpfHzkz8Qz/FgunzKw0PzejFASgg
    ZN/bxRj+ZDwhPg+HXzQesQfqs3RpJFVkUZ2w22X1yhCA0pbEvU6lSQ83lliCSMjm
    ys9FhwYemgtaafSCXx1j+Sg1uxrFol+PpYQElMWGfuoJ5pK/Sp7MkO9cWiIBsgcX
    dsnnedZ6wjFdHD0flp7c2aCvI7V7v1h7tkv3+ytj7Dd/BYmv/h92EF7/VMGI9m+W
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    2aUigVbpyRjAwF7GcLNIOgSNoV59muAGZy0GPK+xjf7DaMVXRKVEBpv7zfv71C3i
    wwdurvwKUW/4xmAqpVadt2uYSE/tBlrJ7IEQJgxThSaqfeywVE/yP3YnKyH9twfC
    26uqQBZJDj3bMkpQVoDgNM876DN7+m45JtqTGGm7E3TzEPTDfCHbx6+7/a83pIlZ
    cbCbl2u59LxE6+Cr3RTDgyh0NMWpeQ/mCVpIBnF71Bbj2OH0QtZNtSvVE8aNyn5E
    S/hMGkMfqT+835fRMzYoxLHlIHeAvXcIhT2SX/2qY/cCggEAOjfZXU5vDwS5H+A4
    O6mKkVRBh2ZImjqY8wH07eBZKYx4ZoLyvwKrk+0BBFw2xEdVAO9BeWc1FbO87teS
    aJaA06SVdF8Q+pLubT4YxjF7eDYmWcA1Gq8kL4EBhr4BJXJh2tpBx2AeuehNYWIW
    w3yK4wmKcOAMP22DAZYDvIldZa7qnjeoPk4BA8DgzJ85CZnHkhWr+Ffj+IZ4uKTh
    rS5qYIMcJpRpLS8JWZjWvjTCJFk+tV1hvVyEsTSOnoOm+E56Fcoups6YxpMLiR72
    zKjjLGtmpUhx1o09of0m2MZzYfPWjjaZtqqONvqv1xuXKKWirUscslTjcMjX6GEl
    N2HwVQKCAQEAiJEfaVZ5koPb5lIlDeNnMeYc7oPi3zwVtBhq3zldX+7/cKru41v2
    50owCPicyNd0W3awqGcO32vMvl41Fdwb/+7HE6Q/xu6DceC4C1Zh5Vztzg01bva8
    7NLWhhSFZ7TJk7NEA6S33tNLnPjavX/vDenXgSoHBux/S1JIVdTdfkKDVFCeDMtj
    12BQkzQ56Izu7U4iIVLFWyElSXOSewFJtxstFwdeVGK7a41aXcuqINg0Uqf32db9
    n5xfUCnM9ApFEtx6UKTzVrIokZ8qAoKjrNCA3tXG2/GRQyqTdW/YqoEq8j8LUpGb
    z7vO78EcVHiaGlRUdEvV+cgOIAkbUeU/pQKCAQEAwjRKFirSPYaIDb5sp1kh1ygb
    3RbH4QBhlHeZk5Zjy5pFtGwhFwx3pyxVGH1h8ETzkH5sclhelMn7vSHjTqziAEg2
    eJ1rirDpSWpuD7r4v527t2CwiE9EvNj4GhnDTB3B/rmuNzvK42iKmzByvuAqjfFU
    O9KqQaRxReVhepUVv9U0pnAAL1Jyzr98thlutsGK0KjHnpcauqyY3+6M+sOBtofK
    bOBt7wpzVyiWrLf09fucJjC8d4NTdcx6uc+r7dRJon9zrcr7IcMs1IhkfTPLznEn
    iTiLHxLcn0xLWqnr8n/Nytn2jqbXURZHXlg6YLW/EdWt4XHdTYWxcu51M10yMw==
    -----END RSA PRIVATE KEY-----
  "ttk_enabled": false
