pm4ml-mojaloop-connector:
  env:
    RESOURCE_VERSIONS: "transfers=1.1,"
    RESERVE_NOTIFICATION: true
    AUTO_ACCEPT_PARTY: false
    AUTO_ACCEPT_QUOTES: false
    
management-api:
  config:
    tlsServerPvtKeyData: |- 
      -----BEGIN RSA PRIVATE KEY-----
      -----END RSA PRIVATE KEY-----
    tlsServerCAData: |-
      -----BEGIN CERTIFICATE-----
      -----END CERTIFICATE-----
    tlsClientPvtKeyData: |-
      -----BEGIN RSA PRIVATE KEY-----
      -----END RSA PRIVATE KEY-----
    tlsClientCSRParametersData: |-
      {
        "subject": {
          "emailAddress": "test@test.com",
          "ST": "test_client",
              "C": "US",
              "L": "test",
              "O": "test",
              "CN": "test_client",
              "OU": "test"
        },
        "extensions": {
          "subjectAltName": {
            "dns": [
              "test"
            ],
            "ips": [
              "test"
            ]
          }
        }
      }
    tlsServerCSRParametersData: |-
      {
        "subject": {
          "emailAddress": "test@test.com",
          "ST": "test_server",
              "C": "US",
              "L": "test",
              "O": "test",
              "CN": "test_server",
              "OU": "test"
        },
        "extensions": {
          "subjectAltName": {
            "dns": [
              "test"
            ],
            "ips": [
              "test"
            ]
          }
        }
      }