"abcdfsp":
  "OAUTH_TOKEN_ENDPOINT": "https://iskm.orcr.mbox-techops.mbox-techops.info.internal:9443/oauth2/token"
  "dfsp_id": "abcdfsp"
  "extgw_client_key": "O9s2WR8UJDaWd2WawUMMgC1VB0wa"
  "extgw_client_secret": "gfZ4NpzVsVSfeNwtRsnLTvTf9RYa"
  "extgw_fqdn": "extgw.orcr.mbox-techops.mbox-techops.info"
  "helm_release_name": "abcdfsp"
  "mcm_auth_enabled": true
  "mcm_auth_pass": "abcdfsppass"
  "mcm_auth_user": "abcdfsp"
  "mcm_host_url": "mcmweb.orcr.mbox-techops.mbox-techops.info"
  "ml_connector_image_tag": "12.0.4"
  "p12_pass_phrase": "samplepass"
  "pm4ml_instance_name": "abcdfsp"
  "pm4ml_subdomain": "mboxtechopsorcrk4s.mbox-techops.mbox-techops.info"
  "private_reg_pass": "changethis"
  "private_reg_url": "modusbox-mbx-docker.jfrog.io"
  "private_reg_user": "mbx-cicd-deployer"
  "jws_private_key": |
    -----BEGIN RSA PRIVATE KEY-----
    -----END RSA PRIVATE KEY-----
  "jws_public_keys":
    "pm4mlreceiverfsp": |
      -----BEGIN PUBLIC KEY-----
      -----END PUBLIC KEY-----
    "pm4mlsenderfsp": |
      -----BEGIN PUBLIC KEY-----
      -----END PUBLIC KEY-----
  "tls_outbound_cacert": |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  "tls_outbound_cert": |-
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  "tls_outbound_privkey": |-
    -----BEGIN RSA PRIVATE KEY-----
    -----END RSA PRIVATE KEY-----
  "ttk_enabled": false
  "ttk_payee_simulator_enabled": false
