---
# File: main.yml - Default variables for k3sup 

### Package
# k3sup state, options: installed, uninstalled 
# (default: installed)
k3sup_state: installed

# Use a specific k3sup version, if set to "false" we will get the latest
# k3sup_release_version: 0.7.0
k3sup_release_version: false

# Install k3sup as a non-root user
k3sup_non_root: false

# URL for GitHub project
k3sup_github_url: https://github.com/alexellis/k3sup

# Installation directory for k3sup
k3sup_install_dir: /usr/local/bin
