- hosts: k3s_master
  become: yes
  collections:
    - community.kubernetes
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  roles:
    - geerlingguy.helm
  tasks:
    - name: Create temporary directory
      tempfile:
        state: directory
        suffix: values
      register: tmpvalues
      tags:
        - loki
    - name: Add helm repo
      shell: |
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update
      tags:
        - loki
    # Upload values files, using the specific version for the cloud_provider if found, or a generic version otherwise  
    - name: Upload helm values
      template: 
        src: "{{ lookup('first_found', findvalues) }}"
        dest: "{{ tmpvalues.path }}/{{ item }}.values.yml"
      vars:
        findvalues:
          - "templates/{{ cloud_provider }}/{{ item }}.values.yml.j2"
          - "templates/{{ item }}.values.yml.j2"
      with_items:
        - loki
      tags:
        - loki
      when: monitoring_stack == 'loki'

    - name: Install loki
      shell: | 
        helm upgrade --install --create-namespace --namespace monitoring loki grafana/loki-stack --version {{ loki_version }} -f "{{ tmpvalues.path}}/loki.values.yml"
      tags:
        - loki
      when: monitoring_stack == 'loki'

    - name: Set grafana admin pw in vault
      shell: |
        VAULT_ROOT_TOKEN=$(cat vault-keys.json | jq -r ".root_token")
        kubectl exec vault-0 -- vault login $VAULT_ROOT_TOKEN
        export graf_admin_pw=$(kubectl get secret -n monitoring loki-grafana -o jsonpath="{.data.admin-password}" | base64 --decode)
        kubectl exec vault-0 -- vault write secrets/grafana/admin pw=$graf_admin_pw
      tags:
        - loki
      when: monitoring_stack == 'loki'